### ISSUE TITLE
Stray Comments

### ISSUE THREAD

**Issue by JonahSMS** [BlueBarracudas/Deliverables#1]
Please remove the comments that were meant to be in the template we used AND ones that are meant to be notes. Such comments are located in chapters 2, 3, 4, and 5, Appendices A, B, and D.

**Comment by davidrash2k** [comment]
Noted. Improved SRS is yet to be uploaded. Improvement on progress.

**Comment by JonahSMS** [comment]
There still are a few left behind (that we still need for reference). Will keep this open until they are removed.
