### ISSUE TITLE
User Story #9 Acceptance Criteria Suggestion

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#10]
I think we could also add "The applicant will only be able to accept, reject, or reschedule the appointment from companies he/she applied to". I'm just foreseeing a problem here where, a company the applicant did not apply to sends an appointment to the applicant. I know that its unlikely to happen, we just need to make sure.

**Comment by davidrash2k** [comment]
Noted.

**Comment by davidrash2k** [comment]
Actually, that is why the Applicant can reject an appointment. As a Company, setting an appointment with an Applicant is a way of saying we are interested in you (it's like a invitation).  So ayun :)
