### ISSUE TITLE
Mandatory Fields

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#13]
For User Stories : 6,  8, 12, 14,15, 16, 20, I think it would be better if the mandatory fields are also specified in each of the acceptance criteria's of these user stories. In that way, it will be easier for those reading the srs to pinpoint which are these fields since, it's hard to assume  which among the fields available are mandatory even if some fields are mentioned in the scenarios.

**Comment by davidrash2k** [comment]
Noted.
