### ISSUE TITLE
Data Types Field

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#14]
For User Stories : 8,14,15,16,20 I suggest that we also include the specific data types of each fields so it will be easier to understand since, some fields may contain different data types depending on the implementation. For example, if one of the fields should contain a string but, due to difference of implementation, the user was just asked to input an integer which is counter checked with the database to figure the value. Verifying if the fields contain the correct data type may not be that efficient since, for a tester, if I don't know the correct data type input, testing this would take up much time because I'd have to input all possible inputs from all possible data types just to check if these user stories would be cleared.

**Comment by davidrash2k** [comment]
Noted.
