### ISSUE TITLE
User Story #9 : 

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#18]
What happens when the user invoked a search for job listings but did not input any keyword, will the search display all possible job listings or is there a restriction that will only display results if a keyword is inputted by the user? 
I just thought of this because what if the applicant was just trying to view all other possible job listings or if the applicant wanted to explore new jobs?

**Comment by davidrash2k** [comment]
Good question. An input must be required to execute a search.
