### ISSUE TITLE
User Story #10

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#19]
Can an applicant still apply for a specific job listing given he/she had previously applied for this but the company rejected it during that instance or will there be a time frame per user to be able to apply for job listings they were previously rejected?

**Comment by davidrash2k** [comment]
There will be a time frame per user to be able to apply for those job listings where they were rejected lets set that to 6 months. These feature is a must have but it is not in the SRS. We will add this feature soon.
