### ISSUE TITLE
User Story #11 : Clarification

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#20]
Is the applicant given an option  to input his/her preferred
schedule ? Because if that's the case, if  he/she decides to reschedule the 
appointment then,  this user story may be too complex though accepting,rejecting, and cancelling an appointment may all have a common result which is, to inform the company regarding the applicants decision regarding an appointment,  including the 3 different options/decision may produce a lot of different possible scenario sequence which might complicate this user story. If that's the plan, I suggest we just separate the rejecting and rescheduling of an appointment by an applicant but, if the applicant will just indicate that he/she wants to reschedule the appointment without any further inputs, then this user story would be fine.

**Comment by davidrash2k** [comment]
For this the Applicant can select reschedule and he / she will suggest the preferred time. It is still up to the Company to set the new schedule.
