### ISSUE TITLE
User Story #16 : Scenario 1

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#21]
I think we can remove this scenario since, the company's decision making/ process  whether to 
hire or reject an applicant is outside the scope of the system. We only care about their final decision which is through their input so in that case, I guess we should not include it in the scenarios.
I think we can replace it,  with "The company chooses an applicant to inform from the list of applicants" or anything that lies on that context.

**Comment by davidrash2k** [comment]
This hire or reject option is our system's way of knowing if an applicant is currently working or not. We retain this feature. This is also a requirement from Experts.
