### ISSUE TITLE
User Story #18 in the SRS: Clarification on Scenario

### ISSUE THREAD

**Issue by JonahSMS** [BlueBarracudas/Deliverables#27]
The scenario doesn't say where exactly the Admin / Super-Admin can do the "button combination" to access the special log-in page.

**Comment by davidrash2k** [comment]
Yeah. So if it doesn't work, then it's all good. It's just what we thought off as a feature. The client never required us to do such.

**Comment by JonahSMS** [comment]
I just meant include where exactly to do the combination in, just to make the SRS consistent.

**Comment by davidrash2k** [comment]
We don't need to put that in the SRS.

**Comment by davidrash2k** [comment]
Consider it as non required additional features.

**Comment by JonahSMS** [comment]
Then remove the user story itself from the SRS if it's non-required.

**Comment by davidrash2k** [comment]
Syfu. What version of the SRS are you checking? scenario 1 states: 1.   The Super Admin / Admin will press a combination of keyboard keys.

**Comment by JonahSMS** [comment]
1.2. Again, I am just saying to put in the SRS where exactly the button combination is to be executed. It doesn't say in the SRS where you input the combination to gain access to the special log-in page.

**Comment by davidrash2k** [comment]
ahh. gets. my bad, sorry. These are things na not specific like Sir Briane said noon. There are parts of the scenarios na describes what should happen but doesn't say how it should be implemented. Ex. The Company chooses the edit option. (It does not say if the company should select a button, link, picture, etc...)
