### ISSUE TITLE
ER Diagram is Clustered

### ISSUE THREAD

**Issue by JonahSMS** [BlueBarracudas/Deliverables#3]
Is it possible to rearrange the entities? Like have the Students and Non-Students be under the Applicants entity to make it easier to tell the inheritance relationship.

**Comment by miloshakes** [comment]
what is this?

On Sun, Feb 22, 2015 at 11:45 AM, davidrash2k notifications@github.com
wrote:

> Assigned #3 https://github.com/BlueBarracudas/Deliverables/issues/3 to
> @miloshakes https://github.com/miloshakes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BlueBarracudas/Deliverables/issues/3#event-239705158.

## 

 http://www.dlsu.edu.ph https://www.facebook.com/DLSU.Manila.100 
http://instagram.com/dlsu https://twitter.com/dlsumanila 
http://dlsumanila.tumblr.com/ http://iblog.lasalle.ph/

DISCLAIMER AND CONFIDENTIALITY NOTICE 
The information contained in this e-mail, including those in its 
attachments, is confidential and intended only for the person(s) or 
entity(ies) to which it is addressed. If you are not an intended recipient, 
you must not read, copy, store, disclose, distribute this message, or act 
in reliance upon the information contained in it. If you received this 
e-mail in error, please contact the sender and delete the material from any 
computer or system. Any views expressed in this message are those of the 
individual sender and may not necessarily reflect the views of De La Salle 
University.

**Comment by JonahSMS** [comment]
Ah, sorry. This was based off of the old ER Diagram, so feel free to disregard it.
