### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by JonahSMS** [BlueBarracudas/Deliverables#6]
In Stakeholder Goals (Chapter 2.1), the first sentence in the "Partner" line makes no sense. Rephrasing is requested.

Also, is this part meant to be written in first person as Experts Prime?

**Comment by davidrash2k** [comment]
Noted. I have changed most of the statement. I copy pasted it directly from Ms. Alfa's reply.
No. Here is the changed statement in the "Partner" line -[Partner -  Hire professionals with certifications. Certifications are proofs that they are knowledgeable and trained in their specific field which will ensure the professionals credibility.]

**Comment by JonahSMS** [comment]
Noted.
