### ISSUE TITLE
ER Diagram: Possible Inheritance?

### ISSUE THREAD

**Issue by JonahSMS** [BlueBarracudas/Deliverables#8]
Can Admin, Applicant, and Company be under one class? They have a few attributes (such as Account_ID, Name, Type) that can be made present in all three so as to avoid having too many classes.

**Comment by nomnomjed** [comment]
This has already been fixed. Please refer to the latest ER Diagram titled "ERD 2.22.2015.png".

**Comment by JonahSMS** [comment]
The issue still stands. Will keep this open for now.
