### ISSUE TITLE
User Story # 5 Acceptance Criteria Suggestion

### ISSUE THREAD

**Issue by RusselJohn** [BlueBarracudas/Deliverables#9]
I think we could also add "Only Admin Approved Non-Expert Student registration will be stored into the system and will be allowed to gain access to the system" since the user story's scope also includes non-expert students registering to gain access to the system. I think this would make it more specific and definite to those who will view the document since its not that clear as of now, if all non expert student registration will be stored in the system all we know is that, they can create and the admin will be notified.

**Comment by davidrash2k** [comment]
Noted.

**Comment by davidrash2k** [comment]
Actually, we still need to store the data from the registration form for the non-Experts Applicants so that the Admin can view their details. If they are accepted then it is stored officially in the system, else their data would be removed from the system. Please respond.

**Comment by JonahSMS** [comment]
What we've talked over about this last Friday:
- If the account is awaiting approval, then it'll be stored in the system temporarily.

*\* If the account is approved, then the account will be stored permanently.
*\* If the account is rejected, then the account will be deleted from the database.

Do correct me if I'm wrong.

**Comment by davidrash2k** [comment]
Noted. I will apply the necessary changes.

**Comment by davidrash2k** [comment]
Changes have been applied. Please check the latest srs.
